services:
  - type: web
    name: bragawork
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgres
      - key: PORT
        value: 5000

databases:
  - name: bragawork-db
    databaseName: bragawork_db
    user: bragawork_user
